#!gmake 

#-----------------------------------------
#Basic Stuff -----------------------------
CC          = g++ 
cc          = gcc

#-----------------------------------------
#Optimization ----------------------------
OPTMAC = -fast

SOURCES=rendering.cpp parser.cpp v_math.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=rendering

#-----------------------------------------
# Mac specific stuff
FRAMEWORK = -framework GLUT
FRAMEWORK += -framework OpenGL
MACLIBS = -lGL -lGLU -lm -lstdc++ 
MACINCS = -L"/System/Library/Frameworks/OpenGL.framework/Libraries"

#-----------------------------------------
CCOPTSMAC = $(OPTMAC) $(MACINCS) -DOSX
LDOPTSMAC = $(OPTMAC) $(MACINCS) $(MACLIBS) -DOSX

#-----------------------------------------
#-----------------------------------------

default: $(EXECUTABLE)

clean:
	/bin/rm -f *.o $(EXECUTABLE)

#-----------------------------------------
#-----------------------------------------

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(OBJECTS) $(LDOPTS) -o $(EXECUTABLE)

.cpp.o:
	$(CC) $< -c $(CCOPTS)

